name: "jokes on issues action"
description: "Greet with random joke on new Issue"
author: "ivan-developer-01"
inputs:
  GITHUB_TOKEN:
    description: "Github Token for authentication"
    required: true

  issue_msg:
    description: "your Customized Issue message , {{author}} and {{joke}} two dynamic variables must be included"
    required: false

  PR_msg:
    description: "your Customized Pull request message , {{author}} and {{joke}} two dynamic variables must be included"
    required: false

  allow_owner:
    description: "allow owners to get jokes too"
    required: false

outputs:
  comment-url:
    description: "The comment URL"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "red"
  icon: "heart"
