

name: "Greet With A Random Joke"
on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: jokes on isssues
        uses: ivan-developer-01/jokes-on-issues-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allow_owner: true
